name: taslema_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  eitherx: ^1.0.3
  get_it: ^7.2.0
  equatable: ^2.0.5
  injectable: ^2.1.0
  retrofit: ^4.0.1
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.2
  localization: ^2.1.0
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  dio: ^5.0.3
  intl: ^0.18.0
  responsive_framework: ^0.2.0
  lottie: ^2.2.0
  bouncing_widget: ^2.0.0
  loading_animation_widget: ^1.2.0+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  connectivity_checker: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/jsons/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300